### ISSUE TITLE
extra dot in file name

### ISSUE THREAD

**Issue by iJahangard** [Lambada10/SongSync#9] opened 2023-07-12 23:44 UTC
in some cases lrc files will have this method of naming
file-name..lrc
the app will add an extra dot before file extension which prevent detecting lrc in music players

**Comment by Lambada10** [comment] 2023-07-13 08:41
I can't reproduce this issue. Could you send the file it happens with?

**Comment by iJahangard** [comment] 2023-07-14 23:29
![Screenshot_20230714-164941_MiXplorer~2](https://github.com/Lambada10/SongSync/assets/67248292/93afee85-eee1-4c82-9160-5b3b50095816)

I face this issue all the time
The song is in flac format which GitHub won't let me upload it 
But if you just rename something to the same name it should have no difference
Anyway if this is still needed, I'll send it some how!

**Comment by nift4** [comment] 2023-07-19 21:39
fixed in 2.0, what app version did u try?

**Comment by iJahangard** [comment] 2023-07-21 07:17
it wasn't v2.0 , so if it was fixed ,I'm just close this issue

**Closed** 2023-07-21 07:17 UTC
Labels: bug
