### ISSUE TITLE
Fails to download all remaining lyrics upon app aspect ratio change.

### ISSUE THREAD

**Issue by u12bdragon** [Lambada10/SongSync#61] opened 2024-03-16 05:30 UTC
When app is in splitscreen mode with another app on the left/right, or is in pop-up (floating on top) mode, and you resize it, it fails to find the rest of the lyrics in batch download mode, immediately. 

1) Put app in splitscreen or pop-up mode via "recents" navbar button.
2) Start batch download of lyrics.
3) Change aspect ratio of app.
4) Lyric downloading fails.

The expected behavior is that nothing should happen, as I'm not closing the app.

Samsung Tab S7 +
Android 13
v3.0.1

**Comment by okgamr** [comment] 2024-05-18 14:19
The dialog before batch downloading for lyrics says clearly not to close the app, and I guess split screen is included, as performing actions on another app while you're downloading the lyrics puts SongSync to run into background (but still have a window of it so you can see what happens and quickly do something between two apps) which is similar to closing the app and leaving it running in the background. Aka the error is caused by leaving the app (and my theory on the split screen is pretty accurate, so don't tell me you didn't leave the app)

**Closed** 2024-08-12 15:49 UTC
Labels: bug
