### ISSUE TITLE
App stopped working altogether 

### ISSUE THREAD

**Issue by Joeeeeb5** [Lambada10/SongSync#39] opened 2023-09-30 08:19 UTC
**Describe the bug**
App cant find lyrics

**To Reproduce**
Search for any song's lyrics

**Expected behavior**
Finds lyrics

**Smartphone (please complete the following information):**
Any

**Additional context**
Stopped working a couple of days ago

**Comment by Lambada10** [comment] 2023-09-30 08:21
Duplicate of #38

**Closed by Lambada10** 2023-09-30 08:21 UTC
Labels: bug
